# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.1.post2.dev1+g1e8dd72.d20220105'
version_tuple = (0, 1, 1, 'dev1', 'g1e8dd72.d20220105')
